[TaskInfo]
Name = "Enforce Bitlocker Encryption Method (Important - Read Notes)"
Notes = "Enforces Bitlocker encryption method. If a machine is found to be out of compliance, this task will decrypt the drive and re-encrypt it with the target method using a recovery password as the key protector. If a previous recovery password is detected, it will be used for the new encryption."
RunsAgainst = "Computers"

[Parameters]
UseScriptParamBlock = true

[Scripts]
Script = "Enforce Bitlocker Encryption Method (Important - Read Notes) Combined Script" # Bitlocker Encryption Method.ps1