[TaskInfo]
Name = "Disable Firefox Password Manager"
Notes = "The script is designed to disable Firefox’s password manager by modifying specific registry keys. "
RunsAgainst = "Computers"
LimitToOnboarding = false
ExecuteSerially = false
AccessLevel = "All"
Reccomended = false
SuperseededBy = {}

[Integration]
IntegrationType = {}

[Parameters]
UseScriptParamBlock = false

[Scripts]
UseCombinedScript = true
Script = "Disable Firefox Password Manager Combined Script" # Use the Disable-FirefoxPasswordManager.ps1 script