[TaskInfo]
Name = "Disable Firefox Telemetry"
Notes = " The script is designed to disable Firefox’s telemetry by modifying specific registry keys. "
RunsAgainst = "Computers"
LimitToOnboarding = false
ExecuteSerially = false
AccessLevel = "All"
Reccomended = false
SuperseededBy = {}

[Integration]
IntegrationType = {}

[Parameters]
UseScriptParamBlock = false

[Scripts]
UseCombinedScript = true
Script = "Disable Firefox Telemetry Combined Script" # Use the Disable-FirefoxTelemetry.ps1 script