[TaskInfo]
Name = "Disable Google Chrome Password Manager"
Notes = "The script is designed to disable Google Chrome’s password manager by modifying specific registry keys."
RunsAgainst = "Computers"
LimitToOnboarding = false
ExecuteSerially = false
AccessLevel = "All"
Reccomended = false
SuperseededBy = {}

[Integration]
IntegrationType = {}

[Parameters]
UseScriptParamBlock = false

[Scripts]
UseCombinedScript = true
Script = "Disable Google Chrome Password Manager Combined Script" # Use the Disable-ChromePasswordManager.ps1 script