[TaskInfo]
Name = "Lockdown Browsers Autofill and Password Manager"
Icon = "lockdown-browsers-autofill-and-password-manager-logo.jpg" # Use lockdown-browsers-autofill-and-password-manager-logo.jpg
Notes = "This task enforces browser security policies by disabling password managers, autofill features (addresses and credit cards), and the Microsoft Edge Wallet. It also removes saved passwords from browser profiles if specified."
RunsAgainst = "Computers"
LimitToOnboarding = false
ExecuteSerially = false
AccessLevel = "All"
Recommended = false
SuperseededBy = ""

[Integration]
IntegrationType = ""

[Parameters]
UseScriptParamBlock = true

[Scripts]
UseCombinedScript = true
[Scripts.CombinedScript]
Script = "lockdown-browsers-autofill-and-password-manager.ps1" # Use lockdown-browsers-autofill-and-password-manager.ps1

[ScriptDetails]
Name = "lockdown-browsers-autofill-and-password-manager"
Type = "Task"
ExecutionContext = "Metascript"
Language = "PowerShell"
OverrideTimeout = false
AccessLevel = "All"