[Installer]
InstallerType = "URL"

[Installer.URL]
InstallerURL = "https://www.plotsoft.com/download/GS_Lite.msi"
PackageType = "Single file installer"

[Installer.URL.SingleFileInstaller]
InstallerFile = "https://www.plotsoft.com/download/GS_Lite.msi"
PackageHash = ""

[SoftwareInfo]
Name = "GhostScript (Lite)"
Notes = "Ghostscript offers native rendering and conversion of all major page description languages to raster and vector files, as well as ASCII text"
RebootRequired = false
Recommended = false

[Licensing]
Setting = "None"

[VersionDetection]
DetectionMethod = "Upgrade Code"

[VersionDetection.UpgradeCode]
UpgradeCode = "86faec72-ea3e-4380-ba1b-52f4ae87cd4c"

[Installation]
Script = "Default MSI Install"

[Uninstallation]
Script = "Uninstall MSI By UpgradeCode"

[UpgradeStrategy]
UpgradeStrategy = "Install Over"

[RepairStrategy]
RepairStrategy = "Uninstall/Install"

[SoftwareAccessLevel]
AccessLevel = "All"

[Hidden]
Hidden = false

[Testing]
TestRequired = false